### MOSTRAR TODAS LAS CANCIONES
GET http://localhost:4000/canciones HTTP/1.1

### MOSTRAR LAS CANCIONES POR ID
GET http://localhost:4000/canciones/102 HTTP/1.1

### INSERTAR UNA NUEVA CANCION
POST http://localhost:4000/canciones/guardar HTTP/1.1
Content-Type: application/json
 
{
    "titulo": "NX1NA",
    "autor": "Los Piojos",
    "album": "unknown",
    "duracion": "4:38",
    "genero": "Rock Nacional",
    "imagen": "www.argentina.gov.ar",
    "linkyoutube": "https://www.youtube.com/watch?v="
}

### ACTUALIZAR UNA CANCION
PUT http://localhost:4000/canciones/actualizar/48 HTTP/1.1
Content-Type: application/json
 
{
    "titulo": "fgfdgfdg",
    "autor": "fhfdghfd",
    "album": "fgfdgfx",
    "duracion": "fgfdgdfg",
    "genero": "gfdgdf",
    "imagen": "",
    "linkyoutube": "https://www.youtube.com/"
}

### ELIMINAR CANCIONES
DELETE http://localhost:4000/canciones/eliminar/98 HTTP/1.1